project:
  type: book
  output-dir: _book

execute:
  freeze: auto

book:
  title: "Applied Geodata Science I"
  subtitle: "Introducing applications of machine learning in Geography and Environmental Sciences"
  author: "Benjamin Stocker"
  date: "13 February 2025"
  page-navigation: true
  chapters:
    - index.qmd
    - logistics.qmd
    - plan.qmd
    #- reportexercises.qmd
  favicon: "figures/favicon.ico"
  twitter-card: true
  search: true
  repo-url: https://github.com/geco-bern/agds1_course/
  sharing: [twitter, facebook]
  navbar:
    title: " "
    logo: "images/logo.png"
    background: "#3A3A3A"
    search: true
    right:
      - text: "Home"
        file: index.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
