# Logistics {#sec-logistics}

## General information

- Lead: Prof. Benjamin Stocker; contributing authors and assistance: Dr. Fabian Bernhard; Geocomputation and Earth Observation, GIUB, UniBe. 
- Course language is English.
- Monday 14.15-16.00 is our presence time, use it for your communication with us.
- No email communications.
- Lecture notes are available as online book at https://geco-bern.github.io/agds_book/. It contains all contents, as reproducible code, with exercises and solutions for self-study. “Report exercises” go into Final Report (see separate document).
- No recordings. It’s all in the book.
- AGDS 1 is required for the Proseminar in Geocomputation and Earth Observation, held in the autumn semester after AGDS 1
- Highly recommended for AGDS 2 (Master course, fall semester 2025)
- Students work on their own laptops which they bring to class.
- This year (spring semester 2025) there is no limit to number of students participating. In future iterations of the course, it will be offered as with a participation limit.
- The course is not formally “creditable” (German: anrechenbar) towards the Master studies in Geography. Requests for crediting can be made and will be handled on an individual basis.
- Master students in Climate Sciences can credit AGDS 1 as Elective Course.
- Registrations for the exam (in the form of the Final Report, see separate document) have to be made until 14 days before the last session (26.05.2025).
- Hybrid class setup: input lectures + flipped classroom + exercises
- To get you set up, we’ll support you with installing all the necessary software on our laptops. But please do get started with installations and setup before our first session, following this:

> Please install essential software needed for this course and check it is running. We will offer support in class, for those that encounter problems. Essential software is (1) **R and RStudio**, follow [this](https://geco-bern.github.io/agds_book/getting_started.html#installing-r-and-rstudio), (2) **git**, follow [this](https://geco-bern.github.io/agds_book/getting_started.html#git-1). Note that additional software for spatial analysis (NetCDF, gdal) is *not* required for AGDS I, i.e. the corresponding sections can be skipped (https://geco-bern.github.io/agds_book/getting_started.html#other-libraries-and-applications).

## Report requirements

### What is part of the report?

Throughout this book, you will find two kinds of exercises:

- Exercises for which we provide solutions. These are NOT part of the final report and solutions are provided for self-study.
- Exercises in sections called “Report Exercise”, which are part of your Final Report. Report Exercises in the form of executable code, generating documents with text and visualisations, will be graded. Report Exercises are:

  1. Chapter 4 (Tidy data)
  2. Chapter 5 (Air quality data visualisation)
  3. Chapter 8 (Collaborating with git)
  4. Chapter 9 (Stepwise regression)
  5. Chapter 10 (KNN)
  6. Chapter 11 (Flux modelling)

The data to solve all these exercises is accessible [here](https://github.com/geco-bern/agds_book/tree/main/book/data).

### How do I hand in the report?

You will send us a link to your GitHub account by email (benjamin.stocker *an der* unibe.ch) that holds the three repositories (directories) containing your code:

- Out of the six report exercises, solve five to.
- Your report repository that holds your report as five .html files that is created from the respective five .Rmd files (one for each Report Exercise, see above).
- Two repositories from the exercise in Chapter 8 (Collaborating with git):
  - Your original repository that your partner’s cloned repository where you accepted a pull request.
  - Your forked repository from your partner on which you opened a pull request.
  - “Hand in” the “report” by pointing us to the URL of your repositories by 09.06.2024 at 8.00 CET.


### How do we grade the report?

For each Report Exercise you can obtain a maximum of 12 points. The final grade is the average across the number of points across Report Exercises (capped at 6, of course).

The grading will consider:

- The code for each Report Exercise needs to be reproducible (3 P).
- Good coding practice (legibility of code, workspace organisation, proper code management) (3 P).
- Quality of visualisations (3 P).
- Interpretations (3 P).

Note that we consider the commit history of your repository to ensure ownership and plausibility of your code contributions. This is to make sure that you cannot copy a repository from someone else and submit it under your name.

**Important**: Reproducibility is key and and we expect that after completing this course, you are able to conduct reproducible workflows! You can ensure that your report is reproducible by letting a colleague or yourself from re-cloning code from GitHub and run your code. This gets you the first 3 P per Report Exercise.


## FAQ

*Can Report Exercises be done as partner or group work?*

No. Each (registered) student hands in their Report Exercise individually. We will check whether submitted Report Exercises have exact duplicates. Note that there is usually no right or wrong way to solve the Report Exercises. The process is important and for our assessment, we will consider the complete implementation of the workflow, the code, the visualisation, and interpretation rather than the exact solution. Do it yourself - it’s your opportunity to practice and gain confidence in mastering the data science workflow.

*Can I use AI for creating the Report Exercises?*

The use of AI is permitted as a aid. However, you are responsible for all contents. AI often fails with details that could make your work unreproducible or generate wrong or unintended results. AI generally generates generic statements. In assessing your Report Exercises, we put a strong focus on these points, your interpretation of the results, and the written and visual communication. Reliance on outputs generated by an AI implies a high risk of failing on these grounds, resulting in poor grades and failure of the course. If we see that your Report Exercises look like a copy of an output of an AI, we apply a very strict grading. This course (and studying at a University in genreal) is your opportunity to learn. Make the best of it and prove us that you’re not replaceable by an AI. It would be sad and a waste of your and our time.


